// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAik4rGxszPlTSfi1tEzP36avSFLqbTrxA',
    appId: '1:959057410574:web:8fb3e484c7c68ce8801a5f',
    messagingSenderId: '959057410574',
    projectId: 'facebookflu',
    authDomain: 'facebookflu.firebaseapp.com',
    storageBucket: 'facebookflu.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA4Im0f1jGCUJRTSlWDaSeCECMPe1JGLs',
    appId: '1:959057410574:android:8887a8d73757a6ff801a5f',
    messagingSenderId: '959057410574',
    projectId: 'facebookflu',
    storageBucket: 'facebookflu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAr960U3di4BEwUyxBHGZP42NA4H-F9qE',
    appId: '1:959057410574:ios:916d8c10a64a34e0801a5f',
    messagingSenderId: '959057410574',
    projectId: 'facebookflu',
    storageBucket: 'facebookflu.appspot.com',
    iosBundleId: 'com.example.facebookFlu',
  );
}
